### ISSUE TITLE
Docstring Data Type

### ISSUE THREAD

**Issue by sy25wang** [UBC-MDS/pystockwatch#11]
Hi everyone, 

- referring to previous projects, notice many teams include data type for parameters/returns. I think it's a good idea we do so too (e.g., _ticker ([str])_)
- Please add pass to the final line of your function so the .py file can run

**Comment by plevchen** [comment]
Great catch. As was communicated during todays meeting, we added `pass` parameters to all our functions and will proceed with numpy style of writing docstrings
