### ISSUE TITLE
No Data: Stock Market OFF for Holidays and Weekends

### ISSUE THREAD

**Issue by helingogo** [UBC-MDS/pystockwatch#19]
There are some dates without stock price data, like weekends and national holidays. I think it might be a common sense for people who want to work on stock related project. But do we need to pay attention for data manipulating and plotting, or do we need to mention this in README.md?

![image](https://user-images.githubusercontent.com/90181776/150090396-4873aa60-a9cb-480b-95fc-0d6820818f65.png)

**Comment by Affrin101** [comment]
I think we should definitely add it in our  README.md as well as in the docstring. Often people might not remember such minute details while giving input. Having such information clearly out there might be of great help

**Comment by plevchen** [comment]
![image](https://user-images.githubusercontent.com/18053738/150229922-d2d41d09-8ade-49eb-ace5-23e17dc6bb93.png)
Plotly handles missing data very well. We do not need to worry about that during plotting. However, it is good catch that we can add one sentence describing this phenomena

**Comment by helingogo** [comment]
Yes! Same here. Then let's just add one sentence to clarify this in README.me!

**Comment by plevchen** [comment]
I added some words regarding this in README. So we can close this issue
