### ISSUE TITLE
Function1: Calculating on "Close" price or "Adj Close" Price?

### ISSUE THREAD

**Issue by helingogo** [UBC-MDS/pystockwatch#20]
For function1 calculation, do we better calculate on "Close" price or "Adj Close" Price?

![image](https://user-images.githubusercontent.com/90181776/150094618-553bcbc7-e204-4d99-84b1-8fbc10f5d046.png)

**Comment by helingogo** [comment]
"The adjusted closing price will give you a better idea of the overall value of the stock and help you make informed decisions about buying and selling, while the closing stock price will tell you the exact cash value of a share of stock at the end of the trading day." By giving this definition, is it better to use "Adj Close" price?

**Comment by plevchen** [comment]
I think we should use regular "Close" option, as it is not clear how they did that adjustment. At least with that example it makes more sense to use "Close", with price 225.24 similar to Open/High and Low prices with 225.0/225.8/223.88. While "Adj Close" price is equal 206.1, which is far off from actual trading price during that day
