### ISSUE TITLE
Need to round off the percent in function 1 to 2 places of decimal

### ISSUE THREAD

**Issue by Affrin101** [UBC-MDS/pystockwatch#27]
Hi @helingogo ,
I used your function to create visualization for-profit percentages of the stock!! Kudos on your work. I had a suggestion, could you please round off the percent to 2 places of decimal so that it looks neat.

**Comment by helingogo** [comment]
Hi affrin, I am still having issue of the poetry in my computer and do not have time to go to find a mac to do additional test after the change. I think you can also round the shown number in 2 decimals when you visualize the plot in Altair.

**Comment by helingogo** [comment]
Somebody ask here about the label formatting issue. I think this would help: [axis rounding decimals](https://github.com/altair-viz/altair/issues/1745).

![image](https://user-images.githubusercontent.com/90181776/150620072-205e5f13-dd8b-434e-a0ed-14edd3e17e99.png)
