### ISSUE TITLE
func3 color calculations need minor fixing

### ISSUE THREAD

**Issue by plevchen** [UBC-MDS/pystockwatch#48]
I just realized that we are using incorrect logic for coloring our bar plots of volume. Color should correspond to price change, not volume change, but bar height should correspond to volume. It can be easily fixed by changing column for difference from "Volume" to "Close" and renaming "Volume_change" to "Price_change" for consistency

**Comment by sy25wang** [comment]
Change the last column named "Indicators" which reflects the price change rather than the volume change
For the price change, I used the Adj Close for each day. 
For the output, the date is index so we only need to return two columns.

**Comment by sy25wang** [comment]
Change the last column named `Indicators` which reflects the price change rather than the volume change
For the price change, I used the `Adj Close` for each day. 
For the output, the date is index so we only need to return two columns.
