### ISSUE TITLE
Discussion on License Choice

### ISSUE THREAD

**Issue by helingogo** [UBC-MDS/pystockwatch#61]

**Comment by sy25wang** [comment]
We had a solid discussion on this for the R package, and we decided to use the same license for our python package as well. Both packages serve the same purpose so we don't see the reason for different licenses.

For this project, MIT can provide the following benefits

- MIT-license is simple and straight-forward
- Permissive that allows other contributors to improve the content of this package
- Clear statements on warranties and liabilities

We also evaluate other options including `GNU GPLv2 license` and `Apache-License`, but comparing to MIT they don't quite fit the purpose of this project.
For a detailed discussion on the license choice, you can refer to our R package https://github.com/UBC-MDS/Rstockwatch/issues/39
